spring.application.name=e-RH
server.servlet.context-path=/api

front.url=http://localhost:4200

# nom de la base de données
spring.datasource.url=jdbc:postgresql://localhost:5432/e_rh

# utilisateur et mot de passe
spring.datasource.username=root
spring.datasource.password=root

# pilote JDBC
spring.datasource.driver-class-name=org.postgresql.Driver

# optionnelle : montrer les requêtes SQL dans la console
spring.jpa.show-sql=true

# optionnelle : stratégie de création des tables (update, create, validate)
spring.jpa.hibernate.ddl-auto=update

# dialecte Hibernate pour PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# token JWt
security.jwt.secret-key=edc0c2ea99387d88f8bea095099ba9a90ac194796414375885c77d59ca850c68
security.jwt.expiration-time=3600000