-- public.departements definition

-- Drop table

-- DROP TABLE public.departements;

CREATE TABLE public.departements (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	departement_name varchar(255) NULL,
	CONSTRAINT departements_pkey PRIMARY KEY (id)
);

INSERT INTO departements (departement_name) VALUES ('GENERALE'), ('AUDITE INTERNE'), ('INFORMATIQUE'), ('FORMATION ET DOCUMENTATION');

-- public.roles definition

-- Drop table

-- DROP TABLE public.roles;

CREATE TABLE public.roles (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	role_name varchar(255) NULL,
	CONSTRAINT roles_pkey PRIMARY KEY (id),
	CONSTRAINT roles_role_name_check CHECK (((role_name)::text = ANY ((ARRAY['ADMIN'::character varying, 'MANAGER'::character varying, 'EMPLOYEE'::character varying])::text[])))
);

INSERT INTO roles (role_name) VALUES ('ADMIN'), ('MANAGER'), ('EMPLOYEE');

-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	email varchar(255) NOT NULL,
	first_name varchar(255) NULL,
	is_active bool NULL,
	last_name varchar(255) NULL,
	"password" varchar(255) NOT NULL,
	departement_id int8 NULL,
	role_id int8 NULL,
	CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT fk9nifrycyqwj59bvb4bkti1d80 FOREIGN KEY (departement_id) REFERENCES public.departements(id),
	CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES public.roles(id)
);


-- public.absences definition

-- Drop table

-- DROP TABLE public.absences;

CREATE TABLE public.absences (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	end_date date NULL,
	start_date date NULL,
	status varchar(255) NULL,
	"type" varchar(255) NULL,
	user_id_id int8 NULL,
	CONSTRAINT absences_pkey PRIMARY KEY (id),
	CONSTRAINT absences_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[]))),
	CONSTRAINT absences_type_check CHECK (((type)::text = ANY ((ARRAY['VACATION'::character varying, 'SICK'::character varying, 'RTT'::character varying])::text[]))),
	CONSTRAINT fkc3vvla80twjmrf7a22cixmtu FOREIGN KEY (user_id_id) REFERENCES public.users(id)
);